/**
 * Author: Chris M. Pérez
 * License: MIT
 */

export const ZOD_TAGS = {
  ZodString: "ZodString",
  ZodNumber: "ZodNumber",
  ZodBigInt: "ZodBigInt",
  ZodBoolean: "ZodBoolean",
  ZodDate: "ZodDate",
  ZodNull: "ZodNull",
  ZodUndefined: "ZodUndefined",
  ZodNaN: "ZodNaN",
  ZodUnknown: "ZodUnknown",
  ZodLiteral: "ZodLiteral",
  ZodArray: "ZodArray",
  ZodTuple: "ZodTuple",
  ZodUnion: "ZodUnion",
  ZodRecord: "ZodRecord",
  ZodObject: "ZodObject",
  ZodEnum: "ZodEnum",
  ZodOptional: "ZodOptional",
  ZodNullable: "ZodNullable",
  ZodDefault: "ZodDefault",
  ZodLazy: "ZodLazy",
} as const;

export const ZOD_VALIDATIONS = {
  MinLength: "MinLength",
  MaxLength: "MaxLength",
  Length: "Length",
  Email: "Email",
  Url: "Url",
  Uuid: "Uuid",
  Cuid: "Cuid",
  Cuid2: "Cuid2",
  Ulid: "Ulid",
  Nanoid: "Nanoid",
  Datetime: "Datetime",
  Ip: "Ip",
  Regex: "Regex",
  Emoji: "Emoji",
  Base64: "Base64",
  Trim: "Trim",
  ToLowerCase: "ToLowerCase",
  ToUpperCase: "ToUpperCase",
  StartsWith: "StartsWith",
  EndsWith: "EndsWith",
  Includes: "Includes",
  Min: "Min",
  Max: "Max",
  Gt: "Gt",
  Gte: "Gte",
  Lt: "Lt",
  Lte: "Lte",
  Int: "Int",
  Positive: "Positive",
  Nonnegative: "Nonnegative",
  Negative: "Negative",
  Nonpositive: "Nonpositive",
  MultipleOf: "MultipleOf",
  Step: "Step",
  Finite: "Finite",
  Safe: "Safe",
} as const;

export const PRISMA_ACTIONS = {
  Cascade: "Cascade",
  Restrict: "Restrict",
  NoAction: "NoAction",
  SetNull: "SetNull",
} as const;

export const PRISMA_FUNCTIONS = {
  AutoIncrement: "autoincrement",
  Now: "now",
  Uuid: "uuid",
  Cuid: "cuid",
  DbGenerated: "dbgenerated",
  Auto: "auto",
  Sequence: "sequence",
  Ulid: "ulid",
  Nanoid: "nanoid",
} as const;

export const PRISMA_TYPES = {
  String: "String",
  Boolean: "Boolean",
  Int: "Int",
  BigInt: "BigInt",
  Float: "Float",
  Decimal: "Decimal",
  DateTime: "DateTime",
  Json: "Json",
  Bytes: "Bytes",
} as const;

export const PRISMA_TAGS = {
  Enum: "Enum",
  Model: "Model",
  AutoIncrement: "AutoIncrement",
  Auto: "Auto",
  Sequence: "Sequence",
  Now: "Now",
  Uuid: "Uuid",
  Cuid: "Cuid",
  Ulid: "Ulid",
  Nanoid: "Nanoid",
  DbGenerated: "DbGenerated",
  Literal: "Literal",
  Id: "Id",
  Unique: "Unique",
  UpdatedAt: "UpdatedAt",
  Ignore: "Ignore",
  Default: "Default",
  Relation: "Relation",
  Index: "Index",
  FullText: "FullText",
  Map: "Map",
  Native: "Native",
  Schema: "Schema",
} as const;
